#!/usr/bin/env bash

# set -x

script_name="$(basename "${0}")"

print_usage() {
	printf '\n%s\n' "${script_name} [-d FOLDER] [-h]"
}

# where the patches are
directory=""

while getopts ":d:h" opt
do
    case ${opt} in
        d)
            directory="${OPTARG}"
            ;;
        h)
            print_usage
            exit 0
            ;;
        \?)
            echo "Unkown option." 1>&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ -z "${directory}" ]]
then
    print_usage 1>&2
    exit 1
fi

git am "${directory}"/*.patch
