#!/usr/bin/env bash

# set -x

print_usage() {
	printf "\\n$(basename "${0}") -d FOLDER [-h]\\n"
}

# where the patches are
directory=""

while getopts ":d:h" opt
do
    case ${opt} in
        d)
            directory="${OPTARG}"
            ;;
        h)
            print_usage
            exit 0
            ;;
        \?)
            echo "Unkown option." 1>&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ -z "${directory}" ]]
then
    print_usage 1>&2
    exit 1
fi

git am "${directory}"/*.patch
